from django import forms
from django.utils.safestring import mark_safe

class quotation(forms.Form):
    name_quote = forms.ChoiceField(choices=(("AC","Accor SA"),
    										("AI","Air Liquide SA"),
    										("AIR","Airbus Group SE"),
    										("MTAS","ArcelorMittal SA"),
    										("ATO","Atos SE"),
    										("CS","AXA SA"),
    										("BNP","BNP Paribas SA"),
    										("EN","Bouygues SA"),
    										("CAP","Capgemini SE"),
    										("CA","Carrefour SA"),
    										("ACA","Credit Agricole SA"),
    										("BN","Danone SA"),
    										("DSY","Dassault Systemes SE"),
    										("ENGI","Engie SA"),
    										("EL","EssilorLuxottica SA"),
    										("RMS","Hermes International SCA"),
    										("KER","Kering SA"),
    										("OR","L’Oreal SA"),
    										("LR","Legrand SA"),
    										("MC","LVMH Moet Hennessy Louis Vuitton SE"),
    										("ML","Compagnie Generale des Etablissements Michelin SCA"),
    										("ORA","Orange SA"),
    										("RI","Pernod Ricard SA"),
    										("UG","Peugeot SA"),
    										("PUB","Publicis Groupe SA"),
    										("RNO","Renault SA"),
    										("SAF","Safran SA"),
    										("SGO","Compagnie de Saint Gobain SA"),
    										("SAN","Sanofi SA"),
    										("SU","Schneider Electric SE"),
    										("GLE","Societe Generale SA"),
    										("SW","Sodexo SA"),
    										("STM","STMicroelectronics NV"),
    										("FTI","TechnipFMC PLC"),
    										("HO","Thales"),
    										("FP","Total SA"),
    										("VIE","Veolia Environnement VE SA"),
    										("DG","Vinci SA"),
    										("VIV","Vivendi SA"),
    										("URWAS","WFD Unibail Rodamco NV")))



class mlmodel(forms.Form):
    name_models = forms.ChoiceField(choices=(("rf","Random Forest"),
    										("gb","Gradient Boosting")))
    name_quote = forms.ChoiceField(choices=(("AC","Accor SA"),
    										("AI","Air Liquide SA"),
    										("AIR","Airbus Group SE"),
    										("MTAS","ArcelorMittal SA"),
    										("ATO","Atos SE"),
    										("CS","AXA SA"),
    										("BNP","BNP Paribas SA"),
    										("EN","Bouygues SA"),
    										("CAP","Capgemini SE"),
    										("CA","Carrefour SA"),
    										("ACA","Credit Agricole SA"),
    										("BN","Danone SA"),
    										("DSY","Dassault Systemes SE"),
    										("ENGI","Engie SA"),
    										("EL","EssilorLuxottica SA"),
    										("RMS","Hermes International SCA"),
    										("KER","Kering SA"),
    										("OR","L’Oreal SA"),
    										("LR","Legrand SA"),
    										("MC","LVMH Moet Hennessy Louis Vuitton SE"),
    										("ML","Compagnie Generale des Etablissements Michelin SCA"),
    										("ORA","Orange SA"),
    										("RI","Pernod Ricard SA"),
    										("UG","Peugeot SA"),
    										("PUB","Publicis Groupe SA"),
    										("RNO","Renault SA"),
    										("SAF","Safran SA"),
    										("SGO","Compagnie de Saint Gobain SA"),
    										("SAN","Sanofi SA"),
    										("SU","Schneider Electric SE"),
    										("GLE","Societe Generale SA"),
    										("SW","Sodexo SA"),
    										("STM","STMicroelectronics NV"),
    										("FTI","TechnipFMC PLC"),
    										("HO","Thales"),
    										("FP","Total SA"),
    										("VIE","Veolia Environnement VE SA"),
    										("DG","Vinci SA"),
    										("VIV","Vivendi SA"),
    										("URWAS","WFD Unibail Rodamco NV")))